### ISSUE TITLE
You can't change configuration 'gwtBuild' because it is already resolved!

### ISSUE THREAD

**Issue by rhazkoomar** [Catalysts/cat-gradle-plugins#5]
Hi,I have set up a multi folder project with build.gradle file as shown in https://github.com/Catalysts/catalysts-gradle-plugins/wiki/cat-gwt ,here is /baseDir/build.gradle

apply plugin: 'cat-gwt'

dependencies {
  gwtBuild (
    [project(path: ':proj1', configuration: 'gwtCompile')]
  )
}

subprojects {
  // apply plugin: 'xxx'

  sourceSets {
    main {
      java {
        srcDir 'src'
      }
      resources {
        srcDir 'src'
      }
    }
  }
}

gwt {
  modules {
    projectX {
      modulename = 'cc.catalysts.gwt.example.projectX'
    }
  }

  eclipse {
    codeSrvStartupUrl 'http://localhost:8888/index.html'
  }
}

but while running the gradle build I get the following error.

D:\Spring3HibernateApp>gradle build
:catalysts-gradle-plugins:compileJava UP-TO-DATE
:catalysts-gradle-plugins:compileGroovy UP-TO-DATE
:catalysts-gradle-plugins:processResources UP-TO-DATE
:catalysts-gradle-plugins:classes UP-TO-DATE
:catalysts-gradle-plugins:jar UP-TO-DATE
:catalysts-gradle-plugins:assemble UP-TO-DATE
:catalysts-gradle-plugins:compileTestJava UP-TO-DATE
:catalysts-gradle-plugins:compileTestGroovy UP-TO-DATE
:catalysts-gradle-plugins:processTestResources UP-TO-DATE
:catalysts-gradle-plugins:testClasses UP-TO-DATE
:catalysts-gradle-plugins:test UP-TO-DATE
:catalysts-gradle-plugins:check UP-TO-DATE
:catalysts-gradle-plugins:build UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Spring3HibernateApp\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'Spring3HibernateApp'.
> You can't change configuration 'gwtBuild' because it is already resolved!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 11.901 secs

please help :(

**Comment by tscheinecker** [comment]
I'm sorry nobody ever responded to your issue - as of now we started completely from scratch with our plugins and dropped obsolete and unused plugins in the progress. The GWT plugin is one of them and therefor any issues will not be fixed. Anybody is free to fork the repository and continue on our old plugin base, but be aware that it wasn't maintained for quite some time and is most probably not even compatible with reasonably up to date versions of gradle.
